# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/home" =
  { device = "/dev/disk/by-uuid/92285ddb-c1d4-4099-a892-f97208b41647";
    fsType = "btrfs";
  };
    
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/cb0c9c4d-70de-4d40-a048-065b80b388f7";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C11C-2AC1";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = 8;
}
